version: "3"
services:
  web: 
    build: .
    command: npm run server:dev
    volumes:
      - .:/home/app/explorer
      - /home/app/explorer/node_modules
    ports: 
      - 3000:3000
      - 5858:5858
    depends_on:
      - db
      - redis
  db:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_PASSWORD=${db__password}
  redis:
    image: redis:4.0-alpine
    # command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - './data/redis:/data'
    ports:
      - 6379:6379
