version: "3"
services:
  web: 
    build: .
    command: npm run dev
    volumes:
      - .:/home/app/explorer
      - /home/app/explorer/node_modules
    ports: 
      - 3000:3000
      - 5858:5858
    depends_on:
      - db
  db:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_PASSWORD=${db__password}